### ISSUE TITLE
Unable to run in Mac M2 machine

### ISSUE THREAD

**Issue by varunrayen** [evanrolfe/trayce_gui#1]
When running the docker container, it throws the following error

```-- END PROG LOAD LOG --
libbpf: prog 'probe_accept4': failed to load: -22
libbpf: failed to load object 'main.bpf.o'
failed to load BPF object: invalid argument
```

```
docker: image with reference docker.io/traycer/trayce_agent:0.0.1 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64.
```

**Comment by evanrolfe** [comment]
Hi, thanks for the bug report. Silly me this has only ever been tested on a Mac with an Intel chip. I'm working on Apple Silicon support now..

**Comment by evanrolfe** [comment]
When you do your docker run command i.e. `docker run --pid=host --privileged -v /var/run/docker.sock:/var/run/docker.sock -it traycer/trayce_agent:0.0.1 -s 192.168.0.1:50051` can you replace `traycer/trayce_agent:0.0.1` with `traycer/trayce_agent:0.0.2` and let me know if that works please? This is a new image which should work on Mac arm64 chips.

**Comment by permanuno** [comment]
i tried `0.0.2` on an M3 macbook pro with sonoma 14.6 and it fails with:

```text
libbpf: prog 'probe_entry_SSL_read': failed to load: -13
libbpf: failed to load object 'main.bpf.o'
failed to load BPF object: permission denied
```

**Comment by evanrolfe** [comment]
@permanuno I've pushed a fix, please run `docker pull traycer/trayce_agent:0.0.2` and try again, thank you.

**Comment by permanuno** [comment]
it works, thank you!

**Comment by evanrolfe** [comment]
great!
